server {
    server_name mc.lucascruz.shop;

    root /var/www/html/prank;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /api/status {
        proxy_pass http://localhost:8080/api/status;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mc.lucascruz.shop/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mc.lucascruz.shop/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mc.lucascruz.shop) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name mc.lucascruz.shop;
    return 404; # managed by Certbot


}
